import { useState, type PointerEvent } from 'react';
import { useSpecs } from '../api/queries';

type CanvasNode = { id: string; label: string; title: string; meta: string; x: number; y: number; tone: string };
const seedNodes: CanvasNode[] = [
  { id: 'agent', label: 'Agent', title: '研究助手', meta: '负责理解任务并组织步骤', x: 12, y: 34, tone: 'blue' },
  { id: 'model', label: '模型', title: 'Qwen · 服务端配置', meta: '生成决策与下一步动作', x: 42, y: 15, tone: 'violet' },
  { id: 'tools', label: '工具', title: '可用工具 3 个', meta: '搜索、计算、文件读取', x: 42, y: 60, tone: 'amber' },
  { id: 'review', label: '运行与回放', title: '可追溯轨迹', meta: '每个输入输出都被记录', x: 76, y: 34, tone: 'green' },
];
const seedEdges = [['agent','model'],['agent','tools'],['model','review'],['tools','review']];

export function WorkspacePage() {
  const { data: specs = [] } = useSpecs();
  const [nodes, setNodes] = useState<CanvasNode[]>(() => { try { return JSON.parse(localStorage.getItem('veridical.canvas.nodes') ?? 'null') ?? seedNodes; } catch { return seedNodes; } }); const [edges, setEdges] = useState<string[][]>(seedEdges); const [selected, setSelected] = useState('agent'); const [drag, setDrag] = useState<string | null>(null); const [zoom, setZoom] = useState(1); const [linking, setLinking] = useState<string | null>(null);
  const node = nodes.find((n) => n.id === selected) ?? nodes[0];
  function addNode(kind: '工具'|'Skill'|'Memory'|'条件' = '工具') { const id = `${kind}-${nodes.length}`; const tone = kind === 'Skill' ? 'violet' : kind === 'Memory' ? 'green' : kind === '条件' ? 'blue' : 'amber'; setNodes((all) => [...all, { id, label: kind, title: `新${kind}节点`, meta: '点击右侧配置输入输出', x: 60, y: 78, tone }]); setSelected(id); }
  function saveDraft() { localStorage.setItem('veridical.canvas.nodes', JSON.stringify(nodes)); localStorage.setItem('veridical.canvas.edges', JSON.stringify(edges)); }
  function updateNode(key: 'title'|'meta', value: string) { setNodes((all) => all.map((n) => n.id === selected ? { ...n, [key]: value } : n)); }
  function port(id: string) { if (!linking) { setLinking(id); return; } if (linking !== id && !edges.some(([a,b]) => a === linking && b === id)) setEdges((all) => [...all, [linking, id]]); setLinking(null); }
  function move(event: PointerEvent, id: string) { if (drag !== id) return; const box = event.currentTarget.getBoundingClientRect(); const x = Math.max(4, Math.min(96, ((event.clientX-box.left)/box.width)*100)); const y = Math.max(8, Math.min(92, ((event.clientY-box.top)/box.height)*100)); setNodes((all) => all.map((n) => n.id === id ? { ...n, x, y } : n)); }
  return <div className="agent-workspace"><header className="workspace-heading"><div><div className="eyebrow">AGENT STUDIO / 工作区</div><h1 className="page-title">研究助手</h1><p className="page-desc">在画布上组织 Agent 的能力，运行后再到回放工作台检查每一步。</p></div><div className="workspace-actions"><button className="btn btn-ghost">保存草稿</button><button className="btn btn-primary">运行测试</button></div></header>
    <div className="workspace-toolbar"><span className="workspace-status"><i/>草稿 · 未发布</span><span>{specs.length} 个 Spec 可用</span><button onClick={()=>addNode('工具')}>＋ 工具</button><button onClick={()=>addNode('Skill')}>＋ Skill</button><button onClick={()=>addNode('Memory')}>＋ Memory</button><button onClick={saveDraft}>保存草稿</button></div>
    <div className="canvas-layout"><section className="agent-canvas" aria-label="Agent 画布" onWheel={(e)=>{e.preventDefault();setZoom(z=>Math.max(.6,Math.min(1.5,z-(e.deltaY>0?.05:-.05))))}} onPointerMove={(e)=>drag&&move(e,drag)} onPointerUp={()=>setDrag(null)} onPointerCancel={()=>setDrag(null)}><div className="canvas-content" style={{transform:`scale(${zoom})`}}><svg className="canvas-lines" viewBox="0 0 1000 600" preserveAspectRatio="none" aria-hidden="true">{edges.map(([a,b])=>{const from=nodes.find(n=>n.id===a);const to=nodes.find(n=>n.id===b);return from&&to?<path key={`${a}-${b}`} d={`M${from.x*10} ${from.y*6} C${(from.x+to.x)*5} ${from.y*6} ${(from.x+to.x)*5} ${to.y*6} ${to.x*10} ${to.y*6}`}/>:null})}</svg>{nodes.map(n=><div key={n.id} className={`canvas-node node-${n.tone} ${selected===n.id?'is-selected':''}`} style={{left:`${n.x}%`,top:`${n.y}%`}} onPointerDown={(e)=>{e.currentTarget.setPointerCapture(e.pointerId);setDrag(n.id);setSelected(n.id)}} onClick={()=>setSelected(n.id)}><span className="node-port node-port-in" onClick={(e)=>{e.stopPropagation();port(n.id)}}/><span className="canvas-node-kicker">{n.label}</span><strong>{n.title}</strong><small>{n.meta}</small><span className="node-port node-port-out" onClick={(e)=>{e.stopPropagation();port(n.id)}}/></div>)}</div><div className="canvas-zoom"><button onClick={()=>setZoom(z=>Math.max(.6,z-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(1.5,z+.1))}>＋</button></div></section><aside className="node-inspector"><div className="inspector-kicker">SELECTED NODE</div><input className="field inspector-title-input" value={node.title} onChange={e=>updateNode('title',e.target.value)}/><textarea className="field inspector-meta-input" value={node.meta} onChange={e=>updateNode('meta',e.target.value)}/><div className="inspector-rule"/><label>节点类型<span>{node.label}</span></label><label>状态<span className="inspector-ok">● 已连接</span></label><label>输入与输出<span>{linking ? '请选择目标节点端口' : '完整记录'}</span></label><button className="btn btn-ghost inspector-edit" onClick={saveDraft}>保存节点配置</button><a className="inspector-link" href="/specs">打开高级 Spec 编辑 →</a></aside></div>
  </div>;
}
